log-level: silent
allow-lan: true
redir-port: 5000
tproxy-port: 5001
find-process-mode: off
unified-delay: true
external-controller: 0.0.0.0:9091
external-ui: ui
secret: B4hdg8YToq
profile: { store-selected: true }
sniffer: { enable: true, sniff: { HTTP: { ports: [80, 8080] }, TLS: { ports: [443, 8443] } }, skip-dst-address: [rule-set:telegram@ipcidr] }

anchors:
  a1: &domain { type: http, format: mrs, behavior: domain, interval: 86400 }
  a2: &ipcidr { type: http, format: mrs, behavior: ipcidr, interval: 86400 }
  a3: &classical { type: http, format: text, behavior: classical, interval: 86400 }
  a4: &inline { type: inline, behavior: classical }
# --- Провайдеры прокси ---
proxy-providers:
  SUB1:
    type: http
    url: "https://de.mmlemeshev.online:2096/subs/fgoyl0g1gqsqs1ka"
    path: ./proxy-providers/subscription.yaml
    interval: 68400
    header:
      User-Agent:
        - "v2rayNG/1.8.0"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

# --- Группы прокси ---
proxy-groups:
  - name: '🚀Auto-Best'
    type: url-test
    use: [subscription]
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    lazy: false

  - name: '🛡️Fallback-Stable'
    type: fallback
    use: [subscription]
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: '⚙️Manual'
    type: select
    use: [subscription]
    proxies: [DIRECT]

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Reddit
    type: select
    icon: https://www.redditstatic.com/shreddit/assets/favicon/192x192.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/main/group-icons/meta.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', PASS, DIRECT]

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Speedtest
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png
    include-all: true
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Viber
    type: select
    icon: https://www.svgrepo.com/show/382714/viber-chat-app.svg
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: CDN
    type: select
    icon: https://www.svgrepo.com/show/396567/globe-with-meridians.svg
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', PASS, DIRECT]
  
  - name: Google
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: GitHub
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', PASS, DIRECT]

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Roblox
    type: select
    icon: https://www.svgrepo.com/show/443377/brand-roblox.svg
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    proxies: ['🚀Auto-Best', '🛡️Fallback-Stable', '⚙️Manual', DIRECT]

# --- НАСТРОЙКИ GEO-ДАННЫХ ---
geox-url:
  geosite: "https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat"
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geoip.dat"

# --- Провайдеры правил ---
rule-providers:
  adlist@domain: { <<: *domain, url: https://github.com/zxc-rv/ad-filter/releases/latest/download/adlist.mrs }
  akamai@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/akamai.mrs }
  akamai@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/akamai@ipcidr.mrs }
  amazon@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/amazon.mrs }
  amazon@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/amazon@ipcidr.mrs }
  category-ai@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs }
  cdn77@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/cdn77@ipcidr.mrs }
  category-ru@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ru.mrs }
  cloudflare@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cloudflare.mrs }
  cloudflare@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/cloudflare@ipcidr.mrs }
  digitalocean@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/digitalocean.mrs }
  digitalocean@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/digitalocean@ipcidr.mrs }
  discord@classical: { <<: *classical, url: https://github.com/zxc-rv/assets/raw/main/rules/discord.list }
  fastly@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/fastly.mrs }
  fastly@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/fastly@ipcidr.mrs }
  gcore@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/gcore@ipcidr.mrs }
  github@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs }
  google@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs }
  google@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/google@ipcidr.mrs }
  hetzner@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hetzner.mrs }
  hetzner@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/hetzner@ipcidr.mrs }
  meta@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/meta.mrs }
  meta@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/meta@ipcidr.mrs }
  oracle@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/oracle.mrs }
  oracle@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/oracle@ipcidr.mrs }
  ovh@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/ovh@ipcidr.mrs }
  reddit@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/reddit.mrs }
  refilter@domain: { <<: *domain, url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs }
  scaleway@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/scaleway@ipcidr.mrs }
  spotify@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs }
  steam@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs }
  speedtest@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/speedtest.mrs }
  telegram@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs }
  telegram@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/telegram@ipcidr.mrs }
  twitch@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitch.mrs }
  twitter@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs }
  vodafone@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/vodafone@ipcidr.mrs }
  vultr@ipcidr: { <<: *ipcidr, url: https://github.com/zxc-rv/zkeenip-rulesets/releases/latest/download/vultr@ipcidr.mrs }
  youtube@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs }
  viber@domain: { <<: *domain, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/viber.mrs }
  viber@classical: { <<: *classical, url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/classical/viber.list }
  user@classical:
    type: inline
    behavior: classical
    payload:
      - DOMAIN-SUFFIX,2ip.io
# --- Правила ---
rules:
  - RULE-SET,adlist@domain,REJECT # Блокировка рекламы
  - AND,((DST-PORT,443),(NETWORK,UDP)),REJECT # Блокировка QUIC

  # --- Roblox ---
  - IP-ASN,22697,Roblox
  - GEOSITE,roblox,Roblox
  - DOMAIN-SUFFIX,roblox.com,Roblox
  - DOMAIN-SUFFIX,rbxcdn.com,Roblox
  - DOMAIN-SUFFIX,rbxinfra.net,Roblox

  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),⚙️Manual # Разблокировка высокого качества на Twitch.tv
  - RULE-SET,category-ai@domain,AI
  - RULE-SET,steam@domain,Steam
  - RULE-SET,spotify@domain,Spotify
  - RULE-SET,reddit@domain,Reddit
  - RULE-SET,youtube@domain,YouTube
  - RULE-SET,twitch@domain,Twitch
  - RULE-SET,twitter@domain,Twitter
  - OR,((RULE-SET,viber@domain),(RULE-SET,viber@classical)),Viber
  - RULE-SET,discord@classical,Discord
  - RULE-SET,speedtest@domain,Speedtest
  - OR,((RULE-SET,meta@domain),(RULE-SET,meta@ipcidr,no-resolve)),Meta
  - OR,((RULE-SET,telegram@domain),(RULE-SET,telegram@ipcidr,no-resolve)),Telegram
  - OR,((RULE-SET,refilter@domain),(RULE-SET,user@classical)),⚙️Manual
  - RULE-SET,github@domain,GitHub
  - OR,((RULE-SET,google@domain),(RULE-SET,google@ipcidr)),Google
  - RULE-SET,category-ru@domain,DIRECT
  - OR,((RULE-SET,amazon@domain),(RULE-SET,amazon@ipcidr)),CDN
  - OR,((RULE-SET,akamai@domain),(RULE-SET,akamai@ipcidr)),CDN
  - OR,((RULE-SET,cloudflare@domain),(RULE-SET,cloudflare@ipcidr)),CDN
  - OR,((RULE-SET,digitalocean@domain),(RULE-SET,digitalocean@ipcidr)),CDN
  - OR,((RULE-SET,fastly@domain),(RULE-SET,fastly@ipcidr)),CDN
  - OR,((RULE-SET,oracle@domain),(RULE-SET,oracle@ipcidr)),CDN
  - OR,((RULE-SET,hetzner@domain),(RULE-SET,hetzner@ipcidr)),CDN
  - RULE-SET,scaleway@ipcidr,CDN
  - RULE-SET,ovh@ipcidr,CDN
  - RULE-SET,vultr@ipcidr,CDN
  - RULE-SET,vodafone@ipcidr,CDN
  - RULE-SET,gcore@ipcidr,CDN
  - RULE-SET,cdn77@ipcidr,CDN
  - MATCH,DIRECT